DROP TABLE IF EXISTS session;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS basket_items;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS products_pictures;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS post_pictures;
DROP TABLE IF EXISTS orders;
DROP TABLE courses;
DROP TABLE categories;

DROP TYPE IF EXISTS platform;
DROP TYPE IF EXISTS user_status;
DROP TYPE IF EXISTS gender;
DROP TYPE IF EXISTS user_role;
DROP TYPE IF EXISTS user_type;
DROP TYPE IF EXISTS product_type;
